const express = require("express");
const morgan = require("morgan");
const logger = require("./middlewares/logger");
const homeRouter = require("./routes/homeRoutes");
const authOperatorRouter = require("./routes/authBusOperator");
const cookieParser = require("cookie-parser");
const authUserRouter = require("./routes/authUserRoutes");
const app = express();
const port = 3000;
app.use(express.json());
app.use(cookieParser());
app.use(logger);
app.use("/", homeRouter);
app.use("/auth/busOperator", authOperatorRouter);
app.use("/auth/user", authUserRouter);
module.exports = app;
